version: '3.9'

services:
  coordinator:
    platform: linux/amd64
    image: citusdata/citus:12.1
    container_name: coordinator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - citus-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  worker1:
    platform: linux/amd64
    image: citusdata/citus:12.1
    container_name: worker1
    environment:
      POSTGRES_PASSWORD: postgres
      COORDINATOR_HOST: coordinator
    depends_on:
      - coordinator
    networks:
      - citus-network

  worker2:
    platform: linux/amd64
    image: citusdata/citus:12.1
    container_name: worker2
    environment:
      POSTGRES_PASSWORD: postgres
      COORDINATOR_HOST: coordinator
    depends_on:
      - coordinator
    networks:
      - citus-network

  api:
    platform: linux/amd64
    build: .
    container_name: api
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    depends_on:
      - coordinator
    networks:
      - citus-network
    volumes:
      - .:/app

networks:
  citus-network:

volumes:
  pgdata: